### ISSUE TITLE
Issue using the package with laravel 5.8

### ISSUE THREAD

**Issue by fanyui** [malicoo/laravel-mesomb#11]
I understand this package is still under developement but For some reason this package doesn't work with laravel 5.8 I try using the pay function on the payment model and I receive an error of Symfony\Component\Debug\Exception\FatalThrowableError thrown with message "Class 'Illuminate\Support\Facades\Http' not found"

Stacktrace:
#56 Symfony\Component\Debug\Exception\FatalThrowableError in /Users/harisu/Downloads/github/laravel/renol/vendor/malico/laravel-mesomb/src/Payment.php:129
#55 Malico\MeSomb\Payment:pay in /Users/harisu/Downloads/github/laravel/renol/app/Http/Controllers/UnauthorizedController.php:112
#54 App\Http\Controllers\UnauthorizedController:createAccount in /Users/harisu/Downloads/github/laravel/renol/vendor/laravel/framework/src/Illuminate/Routing/Controller.php:54
#53 call_user_func_array in /Users/harisu/Downloads/github/laravel/renol/vendor/laravel/framework/src/Illuminate/Routing/Controller.php:54
#52 Illuminate\Routing\Controller:callAction in /Users/harisu/Downloads/github/laravel/renol/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php:45
#51 Illuminate\Routing\ControllerDispatcher:dispatch in /Users/harisu/Downloads/github/laravel/renol/vendor/laravel/framework/src/Illuminate/Routing/Route.php:219
#50 Illuminate\Routing\Route:runController in /Users/harisu/Downloads/github/laravel/renol/vendor/laravel/framework/src/Illuminate/Routing/Route.php:176
#49 Illuminate\Routing\Route:run in /Users/harisu/Downloads/github/laravel/renol/vendor/laravel/framework/src/Illuminate/Routing/Router.php:680
#48 Illuminate\Routing\Router:Illuminate\Routing\{closure} in /Users/harisu/Downloads/github/laravel/renol/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:30
#47 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /Users/harisu/Downloads/github/laravel/renol/app/Http/Middleware/Localization.php:25
#46 App\Http\Middleware\Localization:handle in /Users/harisu/Downloads/github/laravel/renol/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:163
#45 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /Users/harisu/Downloads/github/laravel/renol/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#44 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /Users/harisu/Downloads/github/laravel/renol/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php:41
#43 Illuminate\Routing\Middleware\SubstituteBindings:handle in /Users/harisu/Downloads/github/laravel/renol/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:163
#42 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /Users/harisu/Downloads/github/laravel/renol/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#41 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /Users/harisu/Downloads/github/laravel/renol/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php:75
#40 Illuminate\Foundation\Http\Middleware\VerifyCsrfToken:handle in /Users/harisu/Downloads/github/laravel/renol/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:163
#39 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /Users/harisu/Downloads/github/laravel/renol/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#38 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /Users/harisu/Downloads/github/laravel/renol/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php:49
#37 Illuminate\View\Middleware\ShareErrorsFromSession:handle in /Users/harisu/Downloads/github/laravel/renol/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:163
#36 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /Users/harisu/Downloads/github/laravel/renol/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#35 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /Users/harisu/Downloads/github/laravel/renol/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php:56
#34 Illuminate\Session\Middleware\StartSession:handle in /Users/harisu/Downloads/github/laravel/renol/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:163
#33 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /Users/harisu/Downloads/github/laravel/renol/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#32 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /Users/harisu/Downloads/github/laravel/renol/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php:37
#31 Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse:handle in /Users/harisu/Downloads/github/laravel/renol/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:163
#30 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /Users/harisu/Downloads/github/laravel/renol/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#29 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /Users/harisu/Downloads/github/laravel/renol/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php:66
#28 Illuminate\Cookie\Middleware\EncryptCookies:handle in /Users/harisu/Downloads/github/laravel/renol/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:163
#27 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /Users/harisu/Downloads/github/laravel/renol/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#26 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /Users/harisu/Downloads/github/laravel/renol/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:104
#25 Illuminate\Pipeline\Pipeline:then in /Users/harisu/Downloads/github/laravel/renol/vendor/laravel/framework/src/Illuminate/Routing/Router.php:682
#24 Illuminate\Routing\Router:runRouteWithinStack in /Users/harisu/Downloads/github/laravel/renol/vendor/laravel/framework/src/Illuminate/Routing/Router.php:657
#23 Illuminate\Routing\Router:runRoute in /Users/harisu/Downloads/github/laravel/renol/vendor/laravel/framework/src/Illuminate/Routing/Router.php:623
#22 Illuminate\Routing\Router:dispatchToRoute in /Users/harisu/Downloads/github/laravel/renol/vendor/laravel/framework/src/Illuminate/Routing/Router.php:612
#21 Illuminate\Routing\Router:dispatch in /Users/harisu/Downloads/github/laravel/renol/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php:176
#20 Illuminate\Foundation\Http\Kernel:Illuminate\Foundation\Http\{closure} in /Users/harisu/Downloads/github/laravel/renol/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:30
#19 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /Users/harisu/Downloads/github/laravel/renol/vendor/fideloper/proxy/src/TrustProxies.php:57
#18 Fideloper\Proxy\TrustProxies:handle in /Users/harisu/Downloads/github/laravel/renol/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:163
#17 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /Users/harisu/Downloads/github/laravel/renol/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#16 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /Users/harisu/Downloads/github/laravel/renol/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php:21
#15 Illuminate\Foundation\Http\Middleware\TransformsRequest:handle in /Users/harisu/Downloads/github/laravel/renol/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:163
#14 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /Users/harisu/Downloads/github/laravel/renol/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#13 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /Users/harisu/Downloads/github/laravel/renol/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php:21
#12 Illuminate\Foundation\Http\Middleware\TransformsRequest:handle in /Users/harisu/Downloads/github/laravel/renol/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:163
#11 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /Users/harisu/Downloads/github/laravel/renol/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#10 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /Users/harisu/Downloads/github/laravel/renol/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php:27
#9 Illuminate\Foundation\Http\Middleware\ValidatePostSize:handle in /Users/harisu/Downloads/github/laravel/renol/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:163
#8 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /Users/harisu/Downloads/github/laravel/renol/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#7 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /Users/harisu/Downloads/github/laravel/renol/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php:62
#6 Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode:handle in /Users/harisu/Downloads/github/laravel/renol/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:163
#5 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /Users/harisu/Downloads/github/laravel/renol/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#4 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /Users/harisu/Downloads/github/laravel/renol/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:104
#3 Illuminate\Pipeline\Pipeline:then in /Users/harisu/Downloads/github/laravel/renol/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php:151
#2 Illuminate\Foundation\Http\Kernel:sendRequestThroughRouter in /Users/harisu/Downloads/github/laravel/renol/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php:116
#1 Illuminate\Foundation\Http\Kernel:handle in /Users/harisu/Downloads/github/laravel/renol/public/index.php:55
#0 require_once in /Users/harisu/Downloads/github/laravel/renol/server.php:21
<img width="1440" alt="Screen Shot 2020-11-25 at 15 08 49" src="https://user-images.githubusercontent.com/12346597/100238343-6424c880-2f30-11eb-9ccd-4dd34323f4c8.png">

**Comment by malicoo** [comment]
Please Upgrade your application to Laravel 6 or above. 
Http fascade is only available in laravel 6+.
